### ISSUE TITLE
[Flight SQL] Add headers to the FlightSQL client

### ISSUE THREAD

**Issue by jules-ch** [datafusion-contrib/datafusion-dft#332]
## Context
Some implementation rely on this to route to a specific database.

## Solution

Add a configuration table to specify headers to use with the FlightSQL client.

Could be something like:

```toml
[flightsql_client.headers]
database="some_database"
```

Then add headers to the flightsql client:

```rust
client.add_header(key, value).unwrap();
